### ISSUE TITLE
Topic Presenter's Name is blank

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#94] opened 2015-04-27 11:14 UTC
For example http://www.chipy.org/admin/meetings/topic/120/ is blank.

**Comment by brianray** [comment] 2015-05-05 19:24
Could this be an artifact of a blank name in the User table? http://www.chipy.org/admin/auth/user/?o=3.1

**Comment by emperorcezar** [comment] 2016-07-19 02:01
That is very likely the cause.

**Comment by brianray** [comment] 2017-08-23 17:08
bump

**Comment by JoeJasinski** [comment] 2017-09-07 04:15
This appears to be a duplicate of this issue https://github.com/chicagopython/chipy.org/issues/137, and PR https://github.com/chicagopython/chipy.org/pull/153 resolves this.

**Comment by JoeJasinski** [comment] 2019-03-15 16:52
closing per pr

**Closed** 2019-03-15 16:52 UTC
Labels: type: bug
